version: "3"
services:
  express-service:
    container_name: express-dev
    build: ./express-dev
    ports:
      - "80:3000"
    volumes:
      - ./express-dev:/usr/src/app
    # networks:
    #   - esnet
  elasticsearch-service:
    container_name: elasticsearch-dev
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - 59200:9200
      - 59300:9300
    volumes:
      - ../elasticsearch-data:/usr/share/elasticsearch/data
    # command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
    environment:
      - node.name=es
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - network.host=0.0.0.0
      - cluster.name=testing-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # networks:
    #   - esnet
  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - discovery.seed_hosts=es01
  #     - cluster.initial_master_nodes=es01,es02
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata02:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet

# networks:
#   esnet:
#     driver: bridge