version: "2.2"
services:
  express-service:
    container_name: express-dev
    build: ./express-dev
    ports:
      - "80:3000"
    volumes:
      - ./express-dev:/usr/src/app
    networks:
      - express-es-net
  elasticsearch-service:
    container_name: elasticsearch-dev
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - 59200:9200
      - 59300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - node.name=es
      - cluster.name=testing-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - express-es-net
  mongo-service:
    container_name: mongo-dev
    image: mongo:4.1.10-bionic
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example 
    networks:
      - express-es-net
  admin-mongo-service:
    container_name: admin-mongo-dev
    image: mrvautin/adminmongo:latest
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=1234
    ports:
      - 1234:1234
    links:
      - mongo-service
    networks:
      - express-es-net

volumes:
  elasticsearch-data:
    driver: local

networks:
  express-es-net:
    driver: bridge